--- #YAML:1.0
name:               CodeManager
version:            0.01
abstract:           Yet Another Source Editor
author:
    - Waldemar Biernacki <wb@sao.pl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Copy:           2.13
    File::Copy::Recursive:  0.38
    File::HomeDir:        0.86
    File::Path:           2.07
    Prima:                1.29
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
