---
abstract: 'Yet Another Source Editor'
author:
  - 'Waldemar Biernacki <wb@sao.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CodeManager
no_index:
  directory:
    - t
    - inc
requires:
  File::Copy: 2.13
  File::Copy::Recursive: 0.38
  File::HomeDir: 0.86
  File::Path: 2.07
  Prima: 1.29
version: 0.02
